### ISSUE TITLE
[phenix image] Allow building image directly from vmdb config file

### ISSUE THREAD

**Issue by activeshadow** [sandia-minimega/phenix#11]
---

Originally created by @glattercj on *Wed, 23 Dec 2020 17:19:43 GMT*

---
Add option to pass `phenix image build` an existing vmdb config file to build from, rather than having to first be in the image datastore. Alternatively, allow `phenix image create` the same option so an existing vmdb config can be added to the datastore and then built normally.

**Comment by glattercj** [comment]
Why was this not fix again?
