### ISSUE TITLE
[UI] Error trying to Redeploy VM

### ISSUE THREAD

**Issue by glattercj** [sandia-minimega/phenix#110]
1) Click on name of VM
2) Click on `modify state` > `redeploy`
3) Edit settings as necessary and click `Redeploy`

Expected: VM redeploys using chosen settings
Actual: No change in UI, redeploy modal stays open, receive error in dev tools console.

<img width="1295" alt="Screen Shot 2022-11-12 at 15 19 16" src="https://user-images.githubusercontent.com/8338736/201496896-5fbbfd68-4a6d-4fc3-9d45-e66c05455cab.png">

**Comment by jacdavi** [comment]
Is this currently being worked on? I believe we're seeing something similar, so I might work on fixing this.

**Comment by glattercj** [comment]
@jacdavi Don't believe so. Haven't tested this in a while since I knew it wasn't working, but happy to if you have a fix!

**Comment by activeshadow** [comment]
We have not had a chance to look at this yet @jacdavi.

**Comment by jacdavi** [comment]
@activeshadow Ok no problem. I can work on it next week, just wanted to make sure I wasn't repeating anything.
