### ISSUE TITLE
Unable to VNC into VMs from PhenixWeb

### ISSUE THREAD

**Issue by rfasano** [sandia-minimega/phenix#113]
After clicking on a VM in a running experiment the following URL is displayed, instead of redirecting to a VNC window that gives access to the VM. Seems to only be an issue during startup, after an unknown amount of time the issue resolves itself.
![image](https://user-images.githubusercontent.com/115188805/204394587-f33b05f0-6a0d-4f2b-bfb8-d2584109f688.png)

Here is the corresponding error message given in phenix.log:
2022/11/28 11:13:41 ERROR error.go:87: {"id":"48838a96-f767-4d5e-9d76-1abb06c51f9f","timestamp":"2022-11-28T11:13:41.421740079-07:00","type":"error","source":"myServer","message":"unable to get experiment [object Object] from store","url":"/api/v1/errors/48838a96-f767-4d5e-9d76-1abb06c51f9f"}

**Comment by glattercj** [comment]
@rfasano Do you still have this issue with the latest `main` branch of phenix? If yes, can you post exact steps to reproduce?
