### ISSUE TITLE
Windows startup scripts with graphical components no longer work

### ISSUE THREAD

**Issue by cmulk** [sandia-minimega/phenix#116]
This is because of the commit: 31f8b905b3b27af7fc17401d09533e180c7abc9a

Since the startup scheduled task is now configured to run as SYSTEM, any startup scripts that launch GUI apps or use powershell GUI automations will no longer work, since the scripts execute as SYSTEM and are backgrounded.

I'm not really sure what would be a good solution or workaround for this if the SYSTEM is needed for other tasks. Maybe just manually inject a second startup command that runs as the interactive user like before?

**Comment by activeshadow** [comment]
Hi @cmulk. Yeah, that's probably the best solution (an additional scheduled task). We could inject files that need to be executed as the interactive user into a separate directory.

**Comment by activeshadow** [comment]
@cmulk as an aside, the suggested path forward is outside the purview of phenix proper.

**Comment by cmulk** [comment]
@activeshadow Got it, so I assume the added SYSTEM permissions is necessary going forward (on the phenix startup tasks) for some other reason?

**Comment by activeshadow** [comment]
> @activeshadow Got it, so I assume the added SYSTEM permissions is necessary going forward (on the phenix startup tasks) for some other reason?

@cmulk yes it is. The primary reason that drove this change was the ability to re-arm Windows VMs so their trial license doesn't cause the VM to shut down after 1 hour.

Sorry for the breaking change! :confused:
