### ISSUE TITLE
`npm run serve` results in blank page

### ISSUE THREAD

**Issue by jacdavi** [sandia-minimega/phenix#124]
`npm run serve` in `src/js` now results in a blank page whereas before it used to work and allow hot-reloads. It appears after the changes to `router.js` in de271e33d7743eb7a54b68b2513b99545bc2d973, this no longer works. Not sure what the fix is, or maybe the readme just needs to be updated with new instructions.

**Comment by activeshadow** [comment]
@jacdavi can you try `yarn serve`? We use yarn instead of npm and I'm wondering if that's why we haven't seen this yet.

**Comment by activeshadow** [comment]
It may also be an env variable setting. Either way, yes we'll need to update documentation.

**Comment by jacdavi** [comment]
It looks like the same result with `yarn serve` ([which maybe does the same thing](https://cli.vuejs.org/guide/cli-service.html)?)

So it works fine for you still? That's interesting. It probably is a missing environment variable or something then

**Comment by activeshadow** [comment]
@jacdavi okay so I just tried this and everything works for me as expected (I used `yarn serve` but you're correct in that it shouldn't matter if you use npm or yarn). I have the following in `src/js/.env.development.local`:
```
VUE_APP_AUTH=disabled
VUE_BASE_PATH=/
```

**Comment by activeshadow** [comment]
As an aside, I'm thinking this is a duplicate of #122?

**Comment by jacdavi** [comment]
Thanks that worked perfectly!

And yes, this is a duplicate of #122, I was also seeing the recursion, but didn't realize what was causing it. I'll close this one.
