### ISSUE TITLE
[UI] Enhancement Extend VM Search Fields

### ISSUE THREAD

**Issue by eric-c-wood** [sandia-minimega/phenix#40]
**Describe your feature**
The current VM search only searches for a VM by name. It would be nice to extend the search function to able to ask the following questions/queries:

1. Find all VMs in a specific state (running, stopped, shutdown, etc..)
2. Find all VMs that are currently capturing packets
3. Find all VMs that belong to a specific subnet (192.168.20.1/30, 192.168.3.1/20, etc..)
4. Find all VMs that are running on a specific host
5. Find all VMs with specific tags/metadata.

Search criteria should be able to be combined with verbose Boolean operators such as "and,or,etc.." and have a default Boolean operator when not explicitly specified.

**Feature Details**
Stage of Experiment when feature is active: (Creation, Start, Post Start, Running, Stop, Delete)
stage: Running and Stopped. For a stopped experiment questions 1 and 2 will not apply. For all queries, it might be necessary to wait some period of time before sending the query to the server to avoid flooding the server with incomplete queries.

Where should feature be visible (current phenix tab and general location or propose a new tab, or not visible)
view: The query can be ran from the current search bars on both the running and stopped experiment views.

**Expected behavior**
The running and stopped views will show only the VMs matching the search criteria. The search results can then be used for other actions.

**Comment by activeshadow** [comment]
@eric-c-wood I think all of this was addressed by PR #41 you submitted, correct? If so, please feel free to close this issue!

**Comment by eric-c-wood** [comment]
@activeshadow yes, you are correct.
