### ISSUE TITLE
[UI] Search/Sort Experiment Files

### ISSUE THREAD

**Issue by eric-c-wood** [sandia-minimega/phenix#57]
**Describe your feature**
It would be convenient to be able to search/sort the list of generated experiment files (i.e. packet captures, VM snapshots, memory snapshots, etc..) shown on the `Files` tab of the running  and stopped experiment views.

**Feature Details**
Stage of Experiment when feature is active: (Creation, Start, Post Start, Running, Stop, Delete)
stage: Running and Stopped

Where should feature be visible (current phenix tab and general location or propose a new tab, or not visible)
The existing `Files` tab.

**Expected behavior**
Experiment files can be searched/sorted on the existing `Files` tab for the running and stopped experiment views.  At a minimum, it would be nice to show the file modification date and size.  Most of the fields should be searchable with the exception of the download link.

**Comment by activeshadow** [comment]
Fixed via 515aa6e.
