### ISSUE TITLE
[SOH] List VM names with Vistual Element on Graph

### ISSUE THREAD

**Issue by HannahReinbolt** [sandia-minimega/phenix#59]
Inside the state of health option of phenix, there is a visual graph that is generated to view the current experiment topology. In phenix version 5, the VM names are listed with each node presented within the topology graph. This is very handy for figuring out what is what, quickly instead of selecting a node. In phenix version 6 only the nodes are shown with no VM names. This is a lot more confusing. It would be awesome to have this feature from version 5 also implemented for version 6.

Attached are two pictures showing what the version 5 and 6 graph currently looks like.

**Version 5**
![image](https://user-images.githubusercontent.com/19575139/121394463-f877db00-c916-11eb-96b3-5b6caa361ab3.png)

**Version 6**
![image](https://user-images.githubusercontent.com/19575139/121394561-15aca980-c917-11eb-9641-af9ec88b904c.png)

**Comment by activeshadow** [comment]
@HannahReinbolt this has been fixed (a while ago I believe).
